apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
data:
  FLASK_SECRET_KEY: "MTJhYmNkZWYxMjM0NTY3ODkwYWJjZGVmMTIzNDU2Nzg="  # 생성된 실제 base64 값
  MYSQL_PASSWORD: "dGVzdHBhc3N3b3Jk"  # testpassword를 base64로 인코딩
  REDIS_PASSWORD: "dW5kSUp6RmlSaQ=="  # undIJzFiRi를 base64로 인코딩
  KAFKA_PASSWORD: "" 